kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydeployments
spec:
  replicas: 1
  selector:                       # tells the controller which pods to watch/belong to
    matchLabels:
      name: deployment
  template:
    metadata:
      name: testpod1
      labels:
        name: deployment
    spec:
      containers:
        - name: c00
          image: httpd
          ports:
            - containerPort: 80
---
kind: Service                      # Defines to create Service type Object
apiVersion: v1
metadata:
  name: demoservice
spec:
  ports:
    port: 80                      # Containers port exposed
    targetPort: 80                # Pods port
  selector:
    name: deployment                # Apply this service to any pods which has the specific label
  type: ClusterIP                   # Specifies the service type i.e ClusterIP or NodePort