kind: Deployment
apiVersion: apps/v1
metadata:
    name: nginx-deploy
    namespace: nginx
spec:
  replicas: 2
  selector:    
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-testpod
      labels:
        name: nginx-mydeployments
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports: 
          - containerPort: 80