apiVersion: batch/v1
kind: Job
metadata:
  name: testpod
spec:
  parallelism: 5                           # Runs for pods in parallel
  activeDeadlineSeconds: 10                # Timesout after 30 sec
  template:
    metadata:
      name: testpod
    spec:
      containers:
      - name: counter
        image: centos:7
        command: ["bin/bash", "-c", "echo Technical-Guftgu; sleep 30"]
      restartPolicy: Never